// <auto-generated />
namespace StayFit.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class new20 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(new20));
        
        string IMigrationMetadata.Id
        {
            get { return "201810131021282_new20"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
