// <auto-generated />
namespace StayFit.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class new15 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(new15));
        
        string IMigrationMetadata.Id
        {
            get { return "201810081500126_new15"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
